apm-server:
  host: "0.0.0.0:8200"

output.elasticsearch:
  hosts: ["https://es01:9200"]
  username: "elastic"
  password: "mOfkmnUdds3y-+rarQNc"
  ssl.verification_mode: none

setup.kibana:
  host: "http://kib01:5601"