metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    # Reload module configs as they change:
    reload.enabled: false

metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

# metrics for docker engine, I dont need that 

metricbeat.modules:

- module: docker
  metricsets:
    - container
    - cpu
    - diskio
    - healthcheck
    - info
    - memory
    - network
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
  enabled: true

- module: prometheus
  period: 10s
  metricsets: ["collector"]
  hosts: ["host.docker.internal:4200"]
  metrics_path: /metrics
  enabled: true

processors:
  - add_cloud_metadata: ~

setup.kibana:
  host: "http://kib01:5601"               
  username: "elastic"            
  password: "mOfkmnUdds3y-+rarQNc"           

output.elasticsearch:
  hosts: ['https://es01:9200']
  username: 'elastic'
  password: 'mOfkmnUdds3y-+rarQNc'
  ssl.verification_mode: "none"
